import { useEffect, useState } from 'react';
import api from '../api/client';
import { getError, StatusBadge } from './Ui';

export default function ReportModal({ report, onClose, managerMode = false, onUpdated }) {
  const [comments, setComments] = useState([]); const [comment, setComment] = useState(''); const [error, setError] = useState('');
  useEffect(() => { if (report) api.get(`/reports/${report.id}/comments`).then(({data}) => setComments(data)).catch(err => setError(getError(err))); }, [report]);
  if (!report) return null;
  const review = async(status) => { try { const {data} = await api.patch(`/reports/${report.id}/status`, {status}); onUpdated(data); } catch(err) { setError(getError(err)); } };
  const addComment = async(e) => { e.preventDefault(); try { const {data} = await api.post(`/reports/${report.id}/comments`, {comment}); setComments([...comments,data]); setComment(''); } catch(err) { setError(getError(err)); } };
  return <div className="modal-backdrop-custom" onMouseDown={onClose}><div className="report-modal" onMouseDown={e=>e.stopPropagation()}><div className="d-flex justify-content-between align-items-start"><div><small className="text-muted">{report.employee_name}</small><h3>Report for {new Date(`${report.report_date}T00:00:00`).toLocaleDateString()}</h3></div><button className="btn-close" onClick={onClose}/></div><div className="d-flex gap-3 align-items-center mb-4"><StatusBadge status={report.status}/><span className="text-muted">{report.hours_worked} hours</span></div>{error && <div className="alert alert-danger">{error}</div>}<section><h6>Tasks completed</h6><p>{report.tasks_completed}</p></section><div className="row"><section className="col-md-6"><h6>Blockers</h6><p>{report.blockers || 'None reported'}</p></section><section className="col-md-6"><h6>Next day plan</h6><p>{report.next_day_plan || 'Not provided'}</p></section></div><hr/><h6>Comments</h6><div className="comments">{comments.length ? comments.map(c=><div className="comment" key={c.id}><strong>{c.author_name}</strong><small>{new Date(c.created_at).toLocaleString()}</small><p>{c.comment}</p></div>) : <p className="text-muted">No comments yet.</p>}</div>{managerMode && <><form className="d-flex gap-2 mt-3" onSubmit={addComment}><input className="form-control" value={comment} onChange={e=>setComment(e.target.value)} required placeholder="Add constructive feedback..."/><button className="btn btn-outline-primary">Comment</button></form><div className="d-flex justify-content-end gap-2 mt-4"><button className="btn btn-outline-danger" onClick={()=>review('rejected')}>Reject</button><button className="btn btn-success" onClick={()=>review('approved')}>Approve</button></div></>}</div></div>;
}
