import { useEffect, useState } from 'react';
import api from '../api/client';
import { Alert, getError, PageHeader } from '../components/Ui';

const blank={name:'',email:'',password:'',role:'employee',manager_id:''};
export default function ManageUsers(){
 const [users,setUsers]=useState([]),[managers,setManagers]=useState([]),[form,setForm]=useState(blank),[state,setState]=useState({});
 const load=()=>api.get('/admin/users').then(({data})=>{setUsers(data);setManagers(data.filter(u=>u.role==='manager'&&u.is_active));});
 useEffect(()=>{load();},[]);
 const submit=async(e)=>{e.preventDefault();setState({});try{await api.post('/admin/users',{...form,manager_id:form.manager_id||null});setForm(blank);setState({success:'User created successfully.'});load();}catch(err){setState({error:getError(err)});}};
 const toggle=async(user)=>{await api.patch(`/admin/users/${user.id}`,{is_active:!user.is_active});load();};
 const remove=async(user)=>{if(window.confirm(`Delete ${user.name}? This cannot be undone.`)){await api.delete(`/admin/users/${user.id}`);load();}};
 return <><PageHeader title="Manage users" subtitle="Create and maintain employee and manager accounts."/><div className="row g-4"><div className="col-xl-4"><div className="card form-card"><h5 className="mb-3">Add user</h5><Alert {...state}/><form onSubmit={submit}><label className="form-label">Full name</label><input className="form-control mb-3" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><label className="form-label">Email</label><input className="form-control mb-3" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><label className="form-label">Temporary password</label><input className="form-control mb-3" type="password" minLength="8" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><label className="form-label">Role</label><select className="form-select mb-3" value={form.role} onChange={e=>setForm({...form,role:e.target.value,manager_id:''})}><option value="employee">Employee</option><option value="manager">Manager</option></select>{form.role==='employee'&&<><label className="form-label">Manager</label><select className="form-select mb-4" value={form.manager_id} onChange={e=>setForm({...form,manager_id:e.target.value})}><option value="">Unassigned</option>{managers.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></>}<button className="btn btn-primary w-100">Create user</button></form></div></div><div className="col-xl-8"><div className="card table-card"><div className="table-responsive"><table className="table align-middle mb-0"><thead><tr><th>User</th><th>Role</th><th>Manager</th><th>Status</th><th></th></tr></thead><tbody>{users.filter(u=>u.role!=='admin').map(u=><tr key={u.id}><td><strong>{u.name}</strong><small className="d-block text-muted">{u.email}</small></td><td className="text-capitalize">{u.role}</td><td>{u.manager_name||'—'}</td><td><span className={`status ${u.is_active?'status-approved':'status-rejected'}`}>{u.is_active?'Active':'Inactive'}</span></td><td className="text-end"><button className="btn btn-sm btn-light me-1" onClick={()=>toggle(u)}>{u.is_active?'Disable':'Enable'}</button><button className="btn btn-sm btn-outline-danger" onClick={()=>remove(u)}><i className="bi bi-trash"/></button></td></tr>)}</tbody></table></div></div></div></div></>;
}
